# @package _global_

defaults:
  - _self_
  - GoalDS: gcds #null
  - Env: antmaze-umaze-diverse
  - algo: gotil
  - logger: wandb

seed: 42
num_video_episodes: 2
log_interval: 1_000
eval_interval: 10_000
eval_episodes: 2
save_interval: 250_000
batch_size: 1024
pretrain_steps: 1_000 #1_000_002
